name: Deploy PhonebookApp #워크플로우 이름

on:
  workflow_dispatch:
  
#on:
#  push:  
#    branches:
#      - master #master 또는 프로젝트의 기본 브랜치명 깃허브에 push가 되면 작동

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #소스가져오기

      - name: Set up JDK 17 #업무 이름
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        #run: docker build . -t sophia1106/guestbook:latest
        run: docker build -t sophia1106/phonebooktest:latest .

      - name: Log in to Docker Hub #github secret and variable
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sophia1106/phonebooktest:latest


  SSH:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           sudo docker pull sophia1106/phonebooktest:latest
           sudo docker stop phonebooktest || true
           sudo docker rm phonebooktest || true
           sudo docker run -d --name phonebooktest -p 9090:9090 sophia1106/phonebooktest:latest